apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: sparkbeyond-poc
spec:
  environments:
    - name: dev
      build:
        from: master
  privateImageHubs:
    acrsepessparkbeyondtest.azurecr.io:
      username: acrsepessparkbeyondtest
      email: ctim@equinor.com
  components:
    - name: prediction
      image: acrsepessparkbeyondtest.azurecr.io/sparkbeyond/predbox/2c2487ec-82cd-4617-89f6-c9c820767093:1
      ports:
        - name: http
          port: 8000
      publicPort: http
      resources:
        requests:
          memory: "20000Mi"
          cpu: "6000m"
        limits:
          memory: "320000Mi"
          cpu: "8000m"
      environmentConfig:
        - environment: dev
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 3
          replicas: 1
          monitoring: true
          variables:
            AUTH_ENABLED: false
            EAGERLOAD_FUNCTION_INDEX: "True"
            EAGERLOAD_MODELS: "true"
            EVENTS_ENABLED: "false"
    - name: logimputation
      image: acrsepessparkbeyondtest.azurecr.io/sparkbeyond/predbox/356d7c93-6262-48d9-b067-3a12f216a4ab:17
      ports:
        - name: http
          port: 8000
      publicPort: http
      resources:
        requests:
          memory: "20000Mi"
          cpu: "6000m"
        limits:
          memory: "320000Mi"
          cpu: "8000m"
      environmentConfig:
        - environment: dev
          horizontalScaling:
            minReplicas: 1
            maxReplicas: 3
          replicas: 1
          monitoring: true
          variables:
            AUTH_ENABLED: false
            EAGERLOAD_FUNCTION_INDEX: "True"
            EAGERLOAD_MODELS: "true"
            EVENTS_ENABLED: "false"
  dnsAppAlias:
    environment: dev
    component: prediction
